// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type Exercise struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	MuscleGroup sql.NullString `json:"muscle_group"`
	Difficulty  sql.NullString `json:"difficulty"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ExerciseSet struct {
	ID                string         `json:"id"`
	WorkoutExerciseID string         `json:"workout_exercise_id"`
	SetNumber         int32          `json:"set_number"`
	Reps              sql.NullInt32  `json:"reps"`
	Weight            sql.NullString `json:"weight"`
	RestSeconds       sql.NullInt32  `json:"rest_seconds"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	WeightUnit        sql.NullString `json:"weight_unit"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
}

type MsSession struct {
	ID           string         `json:"id"`
	UserID       int32          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	UserAgent    sql.NullString `json:"user_agent"`
	ClientIp     sql.NullString `json:"client_ip"`
	IsBlocked    bool           `json:"is_blocked"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type MsUser struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	RecStatus string       `json:"rec_status"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type WorkoutExercise struct {
	ID               string         `json:"id"`
	WorkoutSessionID string         `json:"workout_session_id"`
	ExerciseID       string         `json:"exercise_id"`
	Notes            sql.NullString `json:"notes"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
}

type WorkoutSession struct {
	ID              string         `json:"id"`
	UserID          int32          `json:"user_id"`
	SessionDate     time.Time      `json:"session_date"`
	DurationMinutes sql.NullInt32  `json:"duration_minutes"`
	CaloriesBurned  sql.NullInt32  `json:"calories_burned"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}
