// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package repository

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO ms_orders (id, customer_name, total_amount, rec_status) 
VALUES (?, ?, ?, 'A')
`

type CreateOrderParams struct {
	ID           string `json:"id"`
	CustomerName string `json:"customer_name"`
	TotalAmount  string `json:"total_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder, arg.ID, arg.CustomerName, arg.TotalAmount)
}

const createOrderItem = `-- name: CreateOrderItem :execresult
INSERT INTO ms_order_items (order_id, product_id, quantity, price) 
VALUES (?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	OrderID   string `json:"order_id"`
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
	Price     string `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
}

const getOrderWithItems = `-- name: GetOrderWithItems :many
SELECT 
    o.id as order_id, 
    o.customer_name, 
    o.total_amount, 
    o.created_at as order_date,
    oi.id as item_id,
    oi.product_id,
    oi.quantity,
    oi.price as item_price,
    p.name as product_name
FROM ms_orders o
LEFT JOIN ms_order_items oi ON o.id = oi.order_id
LEFT JOIN ms_products p ON oi.product_id = p.id
WHERE o.id = ? AND o.rec_status = 'A'
`

type GetOrderWithItemsRow struct {
	OrderID      string         `json:"order_id"`
	CustomerName string         `json:"customer_name"`
	TotalAmount  string         `json:"total_amount"`
	OrderDate    sql.NullTime   `json:"order_date"`
	ItemID       sql.NullInt32  `json:"item_id"`
	ProductID    sql.NullString `json:"product_id"`
	Quantity     sql.NullInt32  `json:"quantity"`
	ItemPrice    sql.NullString `json:"item_price"`
	ProductName  sql.NullString `json:"product_name"`
}

// Demonstrating JOIN to fetch Order, Items, and Product details
func (q *Queries) GetOrderWithItems(ctx context.Context, id string) ([]GetOrderWithItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderWithItems, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderWithItemsRow
	for rows.Next() {
		var i GetOrderWithItemsRow
		if err := rows.Scan(
			&i.OrderID,
			&i.CustomerName,
			&i.TotalAmount,
			&i.OrderDate,
			&i.ItemID,
			&i.ProductID,
			&i.Quantity,
			&i.ItemPrice,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, customer_name, total_amount, rec_status, created_at, updated_at FROM ms_orders WHERE rec_status = 'A' ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]MsOrder, error) {
	rows, err := q.db.QueryContext(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MsOrder
	for rows.Next() {
		var i MsOrder
		if err := rows.Scan(
			&i.ID,
			&i.CustomerName,
			&i.TotalAmount,
			&i.RecStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
