// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package repository

import (
	"context"
	"database/sql"
)

const checkProductNameExists = `-- name: CheckProductNameExists :one
SELECT EXISTS(
    SELECT 1 FROM ms_products 
    WHERE name = ? AND rec_status = 'A'
)
`

func (q *Queries) CheckProductNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProductNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkProductNameExistsForOther = `-- name: CheckProductNameExistsForOther :one
SELECT EXISTS(
    SELECT 1 FROM ms_products 
    WHERE name = ? AND id != ? AND rec_status = 'A'
)
`

type CheckProductNameExistsForOtherParams struct {
	Name string         `json:"name"`
	ID   sql.NullString `json:"id"`
}

func (q *Queries) CheckProductNameExistsForOther(ctx context.Context, arg CheckProductNameExistsForOtherParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProductNameExistsForOther, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM ms_products 
WHERE rec_status = 'A' 
AND (name LIKE CONCAT('%', ?, '%') OR ? = '')
`

type CountProductsParams struct {
	Search interface{} `json:"search"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts, arg.Search, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :execresult
INSERT INTO ms_products (id, name, price, rec_status) VALUES (?, ?, ?, 'A')
`

type CreateProductParams struct {
	ID    sql.NullString `json:"id"`
	Name  string         `json:"name"`
	Price string         `json:"price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProduct, arg.ID, arg.Name, arg.Price)
}

const deleteProduct = `-- name: DeleteProduct :execresult
UPDATE ms_products SET rec_status = 'D', updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProduct, id)
}

const getProductByID = `-- name: GetProductByID :one
SELECT name, price, rec_status, created_at, updated_at, id FROM ms_products WHERE id = ? AND rec_status = 'A'
`

func (q *Queries) GetProductByID(ctx context.Context, id sql.NullString) (MsProduct, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i MsProduct
	err := row.Scan(
		&i.Name,
		&i.Price,
		&i.RecStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT name, price, rec_status, created_at, updated_at, id FROM ms_products 
WHERE rec_status = 'A' 
AND (name LIKE CONCAT('%', ?, '%') OR ? = '')
LIMIT ? OFFSET ?
`

type ListProductsParams struct {
	Search interface{} `json:"search"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]MsProduct, error) {
	rows, err := q.db.QueryContext(ctx, listProducts,
		arg.Search,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MsProduct
	for rows.Next() {
		var i MsProduct
		if err := rows.Scan(
			&i.Name,
			&i.Price,
			&i.RecStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :execresult
UPDATE ms_products SET name = ?, price = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND rec_status = 'A'
`

type UpdateProductParams struct {
	Name  string         `json:"name"`
	Price string         `json:"price"`
	ID    sql.NullString `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProduct, arg.Name, arg.Price, arg.ID)
}
