// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const blockSession = `-- name: BlockSession :exec
UPDATE ms_sessions SET is_blocked = TRUE WHERE id = ?
`

func (q *Queries) BlockSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, blockSession, id)
	return err
}

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM ms_sessions WHERE expires_at < NOW()
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredSessions)
	return err
}

const createSession = `-- name: CreateSession :execresult
INSERT INTO ms_sessions (
    id, user_id, refresh_token, user_agent, client_ip, expires_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID           string         `json:"id"`
	UserID       int32          `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	UserAgent    sql.NullString `json:"user_agent"`
	ClientIp     sql.NullString `json:"client_ip"`
	ExpiresAt    time.Time      `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.ExpiresAt,
	)
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM ms_sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at FROM ms_sessions WHERE id = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (MsSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i MsSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at FROM ms_sessions WHERE refresh_token = ? LIMIT 1
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (MsSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByRefreshToken, refreshToken)
	var i MsSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
