// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repository

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO ms_user (name, email, password, rec_status) VALUES (?, ?, ?, 'A')
`

type CreateUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Name, arg.Email, arg.Password)
}

const deleteUser = `-- name: DeleteUser :execresult
UPDATE ms_user SET rec_status = 'D', updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, id)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, rec_status, created_at, updated_at FROM ms_user WHERE email = ? AND rec_status = 'A' LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (MsUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i MsUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.RecStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password, rec_status, created_at, updated_at FROM ms_user WHERE id = ? AND rec_status = 'A'
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (MsUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i MsUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.RecStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password, rec_status, created_at, updated_at FROM ms_user WHERE rec_status = 'A'
`

func (q *Queries) ListUsers(ctx context.Context) ([]MsUser, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MsUser
	for rows.Next() {
		var i MsUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.RecStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE ms_user SET name = ?, email = ?, password = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND rec_status = 'A'
`

type UpdateUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	ID       int32  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.ID,
	)
}
