// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const createExercise = `-- name: CreateExercise :execresult
INSERT INTO exercises (id, name, description, muscle_group, difficulty)
VALUES (?, ?, ?, ?, ?)
`

type CreateExerciseParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	MuscleGroup sql.NullString `json:"muscle_group"`
	Difficulty  sql.NullString `json:"difficulty"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createExercise,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.MuscleGroup,
		arg.Difficulty,
	)
}

const createExerciseSet = `-- name: CreateExerciseSet :execresult
INSERT INTO exercise_sets (id, workout_exercise_id, set_number, reps, weight, weight_unit, rest_seconds)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateExerciseSetParams struct {
	ID                string         `json:"id"`
	WorkoutExerciseID string         `json:"workout_exercise_id"`
	SetNumber         int32          `json:"set_number"`
	Reps              sql.NullInt32  `json:"reps"`
	Weight            sql.NullString `json:"weight"`
	WeightUnit        sql.NullString `json:"weight_unit"`
	RestSeconds       sql.NullInt32  `json:"rest_seconds"`
}

func (q *Queries) CreateExerciseSet(ctx context.Context, arg CreateExerciseSetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createExerciseSet,
		arg.ID,
		arg.WorkoutExerciseID,
		arg.SetNumber,
		arg.Reps,
		arg.Weight,
		arg.WeightUnit,
		arg.RestSeconds,
	)
}

const createWorkoutExercise = `-- name: CreateWorkoutExercise :execresult
INSERT INTO workout_exercises (id, workout_session_id, exercise_id, notes)
VALUES (?, ?, ?, ?)
`

type CreateWorkoutExerciseParams struct {
	ID               string         `json:"id"`
	WorkoutSessionID string         `json:"workout_session_id"`
	ExerciseID       string         `json:"exercise_id"`
	Notes            sql.NullString `json:"notes"`
}

func (q *Queries) CreateWorkoutExercise(ctx context.Context, arg CreateWorkoutExerciseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWorkoutExercise,
		arg.ID,
		arg.WorkoutSessionID,
		arg.ExerciseID,
		arg.Notes,
	)
}

const createWorkoutSession = `-- name: CreateWorkoutSession :execresult
INSERT INTO workout_sessions (id, user_id, session_date, duration_minutes, calories_burned, notes)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateWorkoutSessionParams struct {
	ID              string         `json:"id"`
	UserID          int32          `json:"user_id"`
	SessionDate     time.Time      `json:"session_date"`
	DurationMinutes sql.NullInt32  `json:"duration_minutes"`
	CaloriesBurned  sql.NullInt32  `json:"calories_burned"`
	Notes           sql.NullString `json:"notes"`
}

func (q *Queries) CreateWorkoutSession(ctx context.Context, arg CreateWorkoutSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWorkoutSession,
		arg.ID,
		arg.UserID,
		arg.SessionDate,
		arg.DurationMinutes,
		arg.CaloriesBurned,
		arg.Notes,
	)
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, name, description, muscle_group, difficulty, created_at, updated_at FROM exercises WHERE id = ?
`

func (q *Queries) GetExerciseByID(ctx context.Context, id string) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MuscleGroup,
		&i.Difficulty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExerciseSetByID = `-- name: GetExerciseSetByID :one
SELECT id, workout_exercise_id, set_number, reps, weight, weight_unit, rest_seconds, created_at, updated_at FROM exercise_sets WHERE id = ?
`

func (q *Queries) GetExerciseSetByID(ctx context.Context, id string) (ExerciseSet, error) {
	row := q.db.QueryRowContext(ctx, getExerciseSetByID, id)
	var i ExerciseSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutExerciseID,
		&i.SetNumber,
		&i.Reps,
		&i.Weight,
		&i.WeightUnit,
		&i.RestSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFullWorkoutSession = `-- name: GetFullWorkoutSession :many
SELECT 
    ws.id as session_id,
    ws.session_date,
    ws.duration_minutes,
    we.id as workout_exercise_id,
    e.name as exercise_name,
    es.id as set_id,
    es.set_number,
    es.reps,
    es.weight,
    es.weight_unit
FROM workout_sessions ws
LEFT JOIN workout_exercises we ON ws.id = we.workout_session_id
LEFT JOIN exercises e ON we.exercise_id = e.id
LEFT JOIN exercise_sets es ON we.id = es.workout_exercise_id
WHERE ws.id = ?
`

type GetFullWorkoutSessionRow struct {
	SessionID         string         `json:"session_id"`
	SessionDate       time.Time      `json:"session_date"`
	DurationMinutes   sql.NullInt32  `json:"duration_minutes"`
	WorkoutExerciseID sql.NullString `json:"workout_exercise_id"`
	ExerciseName      sql.NullString `json:"exercise_name"`
	SetID             sql.NullString `json:"set_id"`
	SetNumber         sql.NullInt32  `json:"set_number"`
	Reps              sql.NullInt32  `json:"reps"`
	Weight            sql.NullString `json:"weight"`
	WeightUnit        sql.NullString `json:"weight_unit"`
}

// Fetching session, exercises, and sets in one join structure (if needed)
// Note: This might require manual mapping in Go depending on how you want to handle the structure.
func (q *Queries) GetFullWorkoutSession(ctx context.Context, id string) ([]GetFullWorkoutSessionRow, error) {
	rows, err := q.db.QueryContext(ctx, getFullWorkoutSession, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFullWorkoutSessionRow
	for rows.Next() {
		var i GetFullWorkoutSessionRow
		if err := rows.Scan(
			&i.SessionID,
			&i.SessionDate,
			&i.DurationMinutes,
			&i.WorkoutExerciseID,
			&i.ExerciseName,
			&i.SetID,
			&i.SetNumber,
			&i.Reps,
			&i.Weight,
			&i.WeightUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutExerciseByID = `-- name: GetWorkoutExerciseByID :one
SELECT id, workout_session_id, exercise_id, notes, created_at, updated_at FROM workout_exercises WHERE id = ?
`

func (q *Queries) GetWorkoutExerciseByID(ctx context.Context, id string) (WorkoutExercise, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutExerciseByID, id)
	var i WorkoutExercise
	err := row.Scan(
		&i.ID,
		&i.WorkoutSessionID,
		&i.ExerciseID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutSessionByID = `-- name: GetWorkoutSessionByID :one
SELECT id, user_id, session_date, duration_minutes, calories_burned, notes, created_at, updated_at FROM workout_sessions WHERE id = ?
`

func (q *Queries) GetWorkoutSessionByID(ctx context.Context, id string) (WorkoutSession, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutSessionByID, id)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionDate,
		&i.DurationMinutes,
		&i.CaloriesBurned,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT id, name, description, muscle_group, difficulty, created_at, updated_at FROM exercises ORDER BY name ASC
`

func (q *Queries) ListExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MuscleGroup,
			&i.Difficulty,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetsByWorkoutExercise = `-- name: ListSetsByWorkoutExercise :many
SELECT id, workout_exercise_id, set_number, reps, weight, weight_unit, rest_seconds, created_at, updated_at FROM exercise_sets 
WHERE workout_exercise_id = ? 
ORDER BY set_number ASC
`

func (q *Queries) ListSetsByWorkoutExercise(ctx context.Context, workoutExerciseID string) ([]ExerciseSet, error) {
	rows, err := q.db.QueryContext(ctx, listSetsByWorkoutExercise, workoutExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseSet
	for rows.Next() {
		var i ExerciseSet
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutExerciseID,
			&i.SetNumber,
			&i.Reps,
			&i.Weight,
			&i.WeightUnit,
			&i.RestSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutExercisesBySession = `-- name: ListWorkoutExercisesBySession :many
SELECT 
    we.id, we.workout_session_id, we.exercise_id, we.notes, we.created_at, we.updated_at, 
    e.name as exercise_name,
    e.muscle_group
FROM workout_exercises we
JOIN exercises e ON we.exercise_id = e.id
WHERE we.workout_session_id = ?
ORDER BY we.created_at ASC
`

type ListWorkoutExercisesBySessionRow struct {
	ID               string         `json:"id"`
	WorkoutSessionID string         `json:"workout_session_id"`
	ExerciseID       string         `json:"exercise_id"`
	Notes            sql.NullString `json:"notes"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	ExerciseName     string         `json:"exercise_name"`
	MuscleGroup      sql.NullString `json:"muscle_group"`
}

func (q *Queries) ListWorkoutExercisesBySession(ctx context.Context, workoutSessionID string) ([]ListWorkoutExercisesBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutExercisesBySession, workoutSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkoutExercisesBySessionRow
	for rows.Next() {
		var i ListWorkoutExercisesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutSessionID,
			&i.ExerciseID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExerciseName,
			&i.MuscleGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSessionsByUser = `-- name: ListWorkoutSessionsByUser :many
SELECT id, user_id, session_date, duration_minutes, calories_burned, notes, created_at, updated_at FROM workout_sessions WHERE user_id = ? ORDER BY session_date DESC
`

func (q *Queries) ListWorkoutSessionsByUser(ctx context.Context, userID int32) ([]WorkoutSession, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutSession
	for rows.Next() {
		var i WorkoutSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionDate,
			&i.DurationMinutes,
			&i.CaloriesBurned,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExercise = `-- name: UpdateExercise :execresult
UPDATE exercises SET name = ?, description = ?, muscle_group = ?, difficulty = ? WHERE id = ?
`

type UpdateExerciseParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	MuscleGroup sql.NullString `json:"muscle_group"`
	Difficulty  sql.NullString `json:"difficulty"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateExercise,
		arg.Name,
		arg.Description,
		arg.MuscleGroup,
		arg.Difficulty,
		arg.ID,
	)
}

const updateExerciseSet = `-- name: UpdateExerciseSet :execresult
UPDATE exercise_sets SET set_number = ?, reps = ?, weight = ?, weight_unit = ?, rest_seconds = ? WHERE id = ?
`

type UpdateExerciseSetParams struct {
	SetNumber   int32          `json:"set_number"`
	Reps        sql.NullInt32  `json:"reps"`
	Weight      sql.NullString `json:"weight"`
	WeightUnit  sql.NullString `json:"weight_unit"`
	RestSeconds sql.NullInt32  `json:"rest_seconds"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateExerciseSet(ctx context.Context, arg UpdateExerciseSetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateExerciseSet,
		arg.SetNumber,
		arg.Reps,
		arg.Weight,
		arg.WeightUnit,
		arg.RestSeconds,
		arg.ID,
	)
}

const updateWorkoutExercise = `-- name: UpdateWorkoutExercise :execresult
UPDATE workout_exercises SET exercise_id = ?, notes = ? WHERE id = ?
`

type UpdateWorkoutExerciseParams struct {
	ExerciseID string         `json:"exercise_id"`
	Notes      sql.NullString `json:"notes"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateWorkoutExercise(ctx context.Context, arg UpdateWorkoutExerciseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWorkoutExercise, arg.ExerciseID, arg.Notes, arg.ID)
}

const updateWorkoutSession = `-- name: UpdateWorkoutSession :execresult
UPDATE workout_sessions SET session_date = ?, duration_minutes = ?, calories_burned = ?, notes = ? WHERE id = ?
`

type UpdateWorkoutSessionParams struct {
	SessionDate     time.Time      `json:"session_date"`
	DurationMinutes sql.NullInt32  `json:"duration_minutes"`
	CaloriesBurned  sql.NullInt32  `json:"calories_burned"`
	Notes           sql.NullString `json:"notes"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateWorkoutSession(ctx context.Context, arg UpdateWorkoutSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWorkoutSession,
		arg.SessionDate,
		arg.DurationMinutes,
		arg.CaloriesBurned,
		arg.Notes,
		arg.ID,
	)
}
